3D_Visualization
jtr13/cc21fall1 pull request #69
Opened 2021-11-06 02:01 UTC by lewischayworth

This project introduces 3D visualization in R.

2021-11-06 02:02 UTC, lewischayworth commented
This project introduces 3D visualization in R.

2021-11-10 02:55 UTC, HWelinkim requested changes
Hi Zhaoyu, 

Could you please make the following changes?
1. The .Rmd filename can only contain lowercase letters. (Otherwise the filenames do not sort nicely on the repo home page.)
2. The first line should start with a single hashtag #, followed by a single whitespace, and then the title.
3. There should be no additional single hashtag headers in the chapter. (If there are, new chapters will be created.) If you want to use subheadings, you can use ##.

2021-11-10 13:48 UTC, lewischayworth commented
The file is updated. Thank you.

2021-11-10 22:31 UTC, HWelinkim approved these changes

2021-11-10 22:32 UTC, merged